# HTTP Listener Configuration
http.host=0.0.0.0
http.port=8081

# Connected App Credentials for Anypoint Platform Authentication
# These should be provided as runtime properties or environment variables
connectedAppClientId=${connectedAppClientId}
connectedAppClientSecret=${connectedAppClientSecret}

# File Output Configuration
output.file.path=/Users/liang.dai/Downloads/flex_log.txt

# Anypoint MQ Configuration
anypoint.mq.client_id=1e2d736992cc4c2fa97d97ac913b7213
anypoint.mq.client_secret=4Ab4eeE5F16c417Ab0e50EA39F43FDfC
anypoint.mq.region=ap-southeast-2
anypoint.mq.queue.name=demo-anypoint-monitoring-data
